name: Tests CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start the test db
      run: docker-compose up -d atm_machines_test_db
    - name: Build the image
      run: docker-compose build atm_machines_tests
    - name: Run tests
      run: docker-compose run atm_machines_tests
    - name: Down services
      run: docker-compose down
